### PR TITLE
Add PiP button to video tab bar in newer versions

### LINKED ISSUE #43: Pip button in tab bar doesn't show up
See in this video:

https://user-images.githubusercontent.com/87893636/156908342-7cd57da2-45ba-4251-a8eb-b7914aa6f889.MP4

### PR DESCRIPTION
**Pull request by NguyenASang**
This pull request is a hacky way to add PiP button to video tab bar in newer YouTube versions (resolved #43).
If this pull request gets merged, I think we should also remove the `fake version` code.

**Note:** Need to be tested in versions above 17.39.4 (I can't)

### CODE REVIEW

**Comment by NguyenASang** [comment]
Convert to draft since I think I should simplify it.

**Comment by NguyenASang** [comment]
@PoomSmart I think it's done, I tried to simplify the touch detection part but sadly it wasn't possible because I couldn't scroll when adding the touch recognizer to the pip button.

**Comment by NguyenASang** [comment]
@PoomSmart Can you test it on new versions, so we can fix the remaining bugs.

**Comment by PoomSmart** [comment]
Can do, if I have time.

**Comment by PoomSmart** [comment]
Is this ready? I saw additional commits. @NguyenASang

**Comment by NguyenASang** [comment]
@NguyenASang It's ready now.

**Comment by NguyenASang** [comment]
@PoomSmart It actually ready now.

**Comment by PoomSmart** [comment]
@NguyenASang It mostly works, besides the font.

IMG_9A0556DE8C1B-1

**Comment by PoomSmart** [comment]
This works, though: `[UIFont boldSystemFontOfSize:12]`.

**Comment by NguyenASang** [comment]
@PoomSmart Yea, it works on mine also.

**Comment by NguyenASang** [comment]
@PoomSmart The colors are weird in older versions, I will open another pull request to fix it soon.

**Pull request merged**
